### ISSUE TITLE
StandaloneLinePromotedPropertyFixer only applies if there are at least two properties

### ISSUE THREAD

**Issue by gnutix** [symplify/coding-standard#43]
Hello there,

I've noticed that StandaloneLinePromotedPropertyFixer only applies if there are at least two properties in the constructor. I'm unsure if it's a conscious choice or a bug.

Should it be fixed ? Should it be an option to configure the behavior ?
I'm curious to hear your thoughts.

gnutix

**Comment by TomasVotruba** [comment]
Hi,

indeed, it should run on one property as well :+1: 
Could you add the fix?

**Comment by gnutix** [comment]
@TomasVotruba done
