### ISSUE TITLE
Directions on how to use this with CS Fixer

### ISSUE THREAD

**Issue by mdk999** [symplify/coding-standard#56]
Hi. I found this previous issue https://github.com/symplify/coding-standard/issues/52 but it seems to involve modifying vendor files to get it working. I was wondering if you had a different approach to use this with cs fixer. You mentioned you used Laravel, however the project that I'd be using this with does not utilize Laravel. Any direction, thoughts, links on how to pull these fixers into cs fixer would be helpful - Thank you

**Comment by TomasVotruba** [comment]
Hi,

ECS is using container out of the box, and that's how we use Symplify CS there. To achieve the same result in other tools, there is no other way than using DI container (Laravel, pimple, manual etc.).
